Config:
  leader_file: ${oc.env:ROOT}/data/test.csv
  run_id: 
  output_path: ${oc.env:ROOT}/sumo-xml/output
  sumo_gui: true
  fcd_output: "${oc.env:ROOT}/sumo-xml/output/{$Config.run_id}_fcd.xml"

CFParameters: 
  tau: 1
  acceleration: 2.6
  deceleration: 4.5
  speedFactor: 1
  SpeedMode: 31

SUMOParameters:
  step: 0.1
  cmd_line:
    - "-n"
    - "${oc.env:ROOT}/sumo-xml/net.net.xml"
    - "--step-length"
    - "${SUMOParameters.step}"
    - "--no-step-log"
    - "true"

Error:
  val: ${Error.mpe}
  mpe: "???"
  rmsn: "???"
  rmspe: "???"
